* Technology and morality

Technology and morality
Technology is advancing at a blistering pace. Is it causing fall in our
morality? This question is valid now more than in the past.
Enter Computer, Exit morality!
When you decide to buy a computer, you have two options. One is to buy a
branded computer, else you can get it assembled by your nearby computer
shop. At the branded computer price, you can buy a computer with far
superior configuration. This may be because, assembler doesn't pay all
the tax. With branded computer, one gets legal software too. The
assembled kit is loaded with all software, the buyer wants, but this
software is pirated ones.
Later when you need to use application software, we settle for pirated
ones, citing the reason that the legal copy is beyond our reach. We do
not realise that the company, that has developed the software, has spent
lot of money on that and it is not correct to copy it.
Music, video lovers and morality
These days computers are used as a multimedia tool. One can use it to
listen to music or video films can be watched on it. Although music CD's
are available, we do not want to spend for it. One can easily get a
copied CD of the original. We can get the CDs of new films even before
they are released in theatres. Even the cable TV service beams film
videos. We don't even think about it, let alone protest such unethical
practice!
Taking Photostat copies is our birthright?
Whenever we want a content of a book, we go to ‘Xerox' shop and take as
much number of copies of it. Taking Photostat copies of few pages may be
okay, but not the entire book.
Writers and morality
Writers may write about ethics and morality. However, the content may be
simply lifted from a web page or journal. Even reputed newspapers use
pictures from the Internet, even without mentioning the source.
The SMS messages are simply forwarded from one person to another. Ditto
with emails. The author of the joke or quotation is not even mentioned.
Mobile phones embedded with camera phones are the new hits. There is no
need to explain how it is misused in schools and colleges around the
country.
Now tell me how hard it is to be morally upright in this world. One may
have to keep off the technology for doing so. Conscious effort may be
needed to lead a life without compromising with morality. Is there a way
out?
